import os 
import sys 
from pathlib import Path
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
from RoadmapGenerator.llm_engine import stream_response
import ollama

SYSTEM_PROMPT_DIR = r"D:\projects\Student\RoadmapGenerator\system_prompt.md"
LLM = "llama3.1:8b"

def read_sys_prompt(file_path: Path):
    """
    *purpose*: reads system prompt file
    *input*: file_path (path of a system prompt file)
    *output*: conent (file contents)
    """
    try:
        # Open and read the raw markdown syntax
        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read()
            return content
        
    except Exception as e:
        return f"error: {e}"
    
def roadmap_generator(data_of_student: dict):
    """
    *purpose*: generate the detailed roadmap by LLM
    *input: data_of_student (dictionary)
    *output*: detialed roadmap generated by LLM
    """
    try:
        # load system prompt file
        sys_prompt = read_sys_prompt(file_path=SYSTEM_PROMPT_DIR)
        # generate the response
        stream_response(model_nameL=LLM, system_prompt=sys_prompt, student_data=data_of_student)

    except Exception as e:
        print(f"error: {e}")

    except ollama.ResponseError as e:
        print('Error:', e.error)
    